### PR TITLE
Persistent willing2

### PR DESCRIPTION
**Pull request by imanti**
This merge contains only changes to honor willing value from config file; The default willing value (which is enabled) has not been changed. 

There are two commits in this merge:

189f63a - 8021qaz: Honor willing value from config file
Read the willing value of pfc and ets variables directly from the config file before calling set_ieee_hw. In case such value exists and its value is false, then we don't set any pfc/ets data to write to hw.

59c9a54 - 8021qaz: Remove unused variable
Previous commit had introduced an unused variable.

### CODE REVIEW

**Comment by imanti** [comment]
@dmertman 

As requested in PR #12, this PR does not modify the default willing value.

**Comment by dmertman** [comment]
Ron,
Could you do a quick validation on this for me?
Thanks

**Comment by imanti** [comment]
@dmertman Any news with the validation?

**Comment by praeluceo** [comment]
Validation has confirmed that this PR builds fine and is functionally the same as what we were testing previously. Looks good.

**Pull request merged**
