### PR TITLE
lldptool: fix null pointer deference

### PR DESCRIPTION
**Pull request by gaoxingwang**
fix https://github.com/intel/openlldp/issues/87

### CODE REVIEW

**Comment by gaoxingwang** [comment]
PTAL @orgcandman

**Comment by orgcandman** [comment]
How did you generate this error?  I assume that if an issue occurs during weak_readline_init then the rl_handle variable is reinitialized to NULL.  Were you able to reproduce?

I think there is room for cleanup, but I'm curious if this is cleanup or if you observed a real issue here (which would point to some kind of race condition).

**Comment by gaoxingwang** [comment]
My lldpad runs on linux. So, when dlclose(NULL) , Segmentation fault happens.

**Comment by orgcandman** [comment]
Thanks!

**Review by penguin359 — COMMENTED** [review]
lgtm I suspect that this bug was introduced in commit e417cd91eecafc67bc5461ee05975ee926f1ca4f and only surfaces when lldptool/dcbtool are run in interactive mode on a system without libreadline currently installed. Just adding a review that this was accepted so that it is correctly categorized by the OpenSSF scoreboard checker.

**Pull request merged**
